### PR TITLE
 fix abrorber material density

### PR DESCRIPTION
**Pull request by pawlikb**
correction of improper density used to create absorber material mixture ( W,Ni,Cu)
option to use simple solenoid field for non-zero crossing angle

### CODE REVIEW

**Comment by petricm** [comment]
Just as info, since you started to commit to LuCaS here, I have stopped the sync from desy.

**Comment by pawlikb** [comment]
Something wrong ?

**Comment by petricm** [comment]
No, nothing is wrong. Till today I was still syncing LuCaS from desy svn to git, waiting for somebody to say stop, we will use github, but as you started using github, I stopped syncing.

**Comment by pawlikb** [comment]
Thanks, I am new to github and ....

**Comment by petricm** [comment]
OK. Just make sure that everybody now uses LuCaS on github and nobody commits to desy svn.

**Pull request merged**
